# 放置在 ~/.config/fcitx5/conf/classicui.conf
# 修改后执行 systemctl --user restart fcitx5 生效

# 垂直候选列表
Vertical Candidate List=True
# 使用鼠标滚轮翻页
WheelForPaging=True

# 字体大小（调大数值即可）
Font="Sans Serif 16"
MenuFont="Sans Serif 14"
TrayFont="Sans Serif 14"

# 托盘标签颜色
TrayOutlineColor=#000000
TrayTextColor=#ffffff

# 优先使用文字图标
PreferTextIcon=False
# 在图标中显示布局名称
ShowLayoutNameInIcon=True
# 使用输入法的语言来显示文字
UseInputMethodLanguageToDisplayText=True

# 主题（如果 Matugen 不生效，改回 default）
Theme=default
DarkTheme=default-dark
UseDarkTheme=False
UseAccentColor=True

# Wayland 相关
PerScreenDPI=False
ForceWaylandDPI=0
EnableFractionalScale=True
